server.port: 8089
spring:
  data:
    mongodb:
      database: hazloakki_ofertas
      username: admin
      password: admin
      port: 27017
      host: localhost
    
hazloakki.aws.access_key_id: xxxx
hazloakki.aws.secret_access_key: xxxx
hazloakki.s3.region: us-east-1