server.port: 8089
spring:
  data:
    mongodb:
      database: hazloakki_ofertas
      port: 27017
      host: localhost
    
hazloakki.aws.access_key_id: 
hazloakki.aws.secret_access_key: 
hazloakki.s3.region: us-east-1