apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: analytic-db-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: analytic-db-pv