apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: business-db-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: business-db-pv