apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: login-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: login-app
        tier: backend
    spec:
      containers:
      - name: login
        image: iortizf/login-ms:0.0.1-snapshot
        ports:
        - containerPort: 8087