apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-app
        tier: backend
    spec:
      containers:
      - name: catalog
        image: iortizf/catalog-ms:0.0.3-snapshot
        ports:
        - containerPort: 8088