apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: catalog-db-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: catalog-db-pv