apiVersion: v1
kind: Service
metadata:
  name: business-service
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: business
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: business-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: business
        tier: backend
    spec:
      containers:
      - name: business
        image: iortizf/business-ms:0.0.1-snapshot
        ports:
        - containerPort: 8086 