server.port: 8088
spring:
  application:
    name: catalog-ms
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update 
  datasource:
    platform: postgres
    url: jdbc:postgresql://catalog-db-svc/hazloakki_catalogos
    username: admin
    password: admin
    driverClassName: org.postgresql.Driver