apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  ports:
  - port: 8087
    targetPort: 8087
  selector:
    app: login
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: login-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: login
        tier: backend
    spec:
      containers:
      - name: login
        image: iortizf/login-ms:0.0.1-snapshot
        ports:
        - containerPort: 8087